### ISSUE TITLE
Will this ane keep updating to the latest version of amplitude?

### ISSUE THREAD

**Issue by jimmymjing** [DigitalStrawberry/ANE-Amplitude#1]
Hello,
Thanks so much for creating this ANE. I would love to use it in our game. I find it is not the latest version of Amplitude. Will you later update this ane? Thanks so much.

**Comment by ecornbower** [comment]
Thanks for the compliment. We typically only update the SDK when a major feature has been released or significant bug has been fixed, so do not expect the SDK to be always up to date with the Amplitude SDK. The ANE is fully open-source so you are welcome to make a pull request with changes if you feel we need to support something that we don't yet.

It has been a while since we updated the SDKs - @marpies can you take a look and see if we can update this to the latest version?

**Comment by marpies** [comment]
Sure, I will take a look at it.

**Comment by marpies** [comment]
The SDKs have been updated to the latest version for both iOS and Android.

**Comment by jimmymjing** [comment]
Thanks so much!! can't wait to give this a try!
